import type { CreationSkill, PromptRuleSet } from '@hitframe/shared';

const PRODUCT_RULES: PromptRuleSet = {
  requiredSections: ['subject', 'scene', 'composition', 'lighting', 'fidelity', 'negative'],
  defaultNegativeConstraints: [
    '不要生成第二个商品',
    '不要改变商品外观、比例、材质、Logo 或包装文字',
    '不要生成随机品牌文字或乱码',
  ],
  textLayerPolicy: 'no_text',
};

const CONTENT_RULES: PromptRuleSet = {
  requiredSections: ['subject', 'scene', 'composition', 'lighting', 'negative'],
  defaultNegativeConstraints: ['不要生成水印', '不要生成随机文字', '不要出现多余主体'],
  textLayerPolicy: 'no_text',
};

/**
 * Checked-in Skill registry. Skill is declarative data, never executable user code.
 * External skills can be adapted into this shape only after license and schema review.
 */
export const CREATION_SKILLS: readonly CreationSkill[] = [
  {
    id: 'skill_general_image',
    name: '通用图片创作',
    description: '将自然语言需求整理为可执行的图片创作说明。',
    category: 'content',
    outputType: 'image',
    generationMode: 't2i',
    requiredReferences: [],
    optionalReferences: ['style', 'background'],
    defaultRatio: '1:1',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: CONTENT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_product_background',
    name: '商品换背景',
    description: '锁定商品主体，替换为商业摄影场景。',
    category: 'product',
    outputType: 'image',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['background', 'style', 'logo'],
    defaultRatio: '4:3',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_model_try_on',
    name: '模特上身 / 真人试穿',
    description: '将服装或配饰自然呈现于人物身上，保持商品和人物身份。',
    category: 'product',
    outputType: 'image',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['person', 'style'],
    defaultRatio: '3:4',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_ecommerce_poster',
    name: '电商海报',
    description: '生成完整饱满的商品营销主视觉；文字由用户后续决定是否叠加。',
    category: 'product',
    outputType: 'image',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['logo', 'style'],
    defaultRatio: '3:4',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_xhs_cover',
    name: '小红书封面',
    description: '按小红书竖版传播构图生成单张商品封面。',
    category: 'content',
    outputType: 'image',
    generationMode: 'i2i',
    supportsTextOnly: true,
    requiredReferences: ['product'],
    optionalReferences: ['logo', 'style'],
    defaultRatio: '3:4',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_product_atmosphere',
    name: '产品氛围广告',
    description: '围绕商品材质、场景和品牌氛围生成广告主视觉。',
    category: 'product',
    outputType: 'image',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['background', 'style', 'logo'],
    defaultRatio: '4:3',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_xhs_set',
    name: '小红书多图组',
    description: '规划统一视觉的多张内容图，每张图有独立画面任务。',
    category: 'content',
    outputType: 'image_set',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['style', 'logo'],
    defaultRatio: '3:4',
    defaultCandidateCount: 4,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_grid',
    name: '宫格图 / 九宫格',
    description: '生成具有统一主题和分格关系的宫格视觉。',
    category: 'content',
    outputType: 'image',
    generationMode: 'i2i',
    requiredReferences: ['product'],
    optionalReferences: ['style'],
    defaultRatio: '1:1',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: PRODUCT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_article_illustration',
    name: '文章配图',
    description: '根据已有主题或文章摘要生成配图，不生成文章正文。',
    category: 'content',
    outputType: 'image',
    generationMode: 't2i',
    requiredReferences: [],
    optionalReferences: ['style'],
    defaultRatio: '4:3',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: CONTENT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
  {
    id: 'skill_infographic',
    name: '信息图',
    description: '生成完整的信息结构视觉；准确文字由用户后续决定是否叠加。',
    category: 'content',
    outputType: 'image',
    generationMode: 't2i',
    requiredReferences: [],
    optionalReferences: ['style', 'logo'],
    defaultRatio: '4:3',
    defaultCandidateCount: 1,
    defaultQuality: 'standard',
    promptRules: CONTENT_RULES,
    source: 'hitframe',
    license: 'HitFrame',
    version: 1,
  },
];

export function findCreationSkill(skillId?: string): CreationSkill | undefined {
  return CREATION_SKILLS.find((skill) => skill.id === skillId);
}
